export const languages = {
  iso6391: [
    { language: 'аҧсуа бызшәа, аҧсшәа', languageCode: 'abk' },
    { language: 'Afar', languageCode: 'aa' },
    { language: 'Afrikaans', languageCode: 'af' },
    { language: 'Akan', languageCode: 'ak' },
    { language: 'Albanian', languageCode: 'sq' },
    { language: 'Amharic', languageCode: 'am' },
    { language: 'Arabic', languageCode: 'ar' },
    { language: 'Aragonese', languageCode: 'an' },
    { language: 'Armenian', languageCode: 'hy' },
    { language: 'Assamese', languageCode: 'as' },
    { language: 'Avaric', languageCode: 'av' },
    { language: 'Avestan', languageCode: 'ae' },
    { language: 'Aymara', languageCode: 'ay' },
    { language: 'Azerbaijani', languageCode: 'az' },
    { language: 'Bambara', languageCode: 'bm' },
    { language: 'Bashkir', languageCode: 'ba' },
    { language: 'Basque', languageCode: 'eu' },
    { language: 'Belarusian', languageCode: 'be' },
    { language: 'Bengali', languageCode: 'bn' },
    { language: 'Bihari languages', languageCode: 'bh' },
    { language: 'Bislama', languageCode: 'bi' },
    { language: 'Bosnian', languageCode: 'bs' },
    { language: 'Breton', languageCode: 'br' },
    { language: 'Bulgarian', languageCode: 'bg' },
    { language: 'Burmese', languageCode: 'my' },
    { language: 'Catalan, Valencian', languageCode: 'ca' },
    { language: 'Chamorro', languageCode: 'ch' },
    { language: 'Chechen', languageCode: 'ce' },
    { language: 'Chichewa, Chewa, Nyanja', languageCode: 'ny' },
    { language: 'Chinese', languageCode: 'zh-CN' },
    { language: 'Chuvash', languageCode: 'cv' },
    { language: 'Cornish', languageCode: 'kw' },
    { language: 'Corsican', languageCode: 'co' },
    { language: 'Cree', languageCode: 'cr' },
    { language: 'Croatian', languageCode: 'hr' },
    { language: 'Czech', languageCode: 'cs' },
    { language: 'Danish', languageCode: 'da' },
    { language: 'Divehi, Dhivehi, Maldivian', languageCode: 'dv' },
    { language: 'Dutch, Flemish', languageCode: 'nl' },
    { language: 'Dzongkha', languageCode: 'dz' },
    { language: 'English', languageCode: 'en' },
    { language: 'Esperanto', languageCode: 'eo' },
    { language: 'Estonian', languageCode: 'et' },
    { language: 'Ewe', languageCode: 'ee' },
    { language: 'Faroese', languageCode: 'fo' },
    { language: 'Fijian', languageCode: 'fj' },
    { language: 'Finnish', languageCode: 'fi' },
    { language: 'French', languageCode: 'fr-FR' },
    { language: 'Fulah', languageCode: 'ff' },
    { language: 'Galician', languageCode: 'gl' },
    { language: 'Georgian', languageCode: 'ka' },
    { language: 'German', languageCode: 'de-DE' },
    { language: 'Greek (modern)', languageCode: 'el' },
    { language: 'Guaraní', languageCode: 'gn' },
    { language: 'Gujarati', languageCode: 'gu' },
    { language: 'Haitian, Haitian Creole', languageCode: 'ht' },
    { language: 'Hausa', languageCode: 'ha' },
    { language: 'Hebrew (modern)', languageCode: 'he' },
    { language: 'Herero', languageCode: 'hz' },
    { language: 'Hindi', languageCode: 'hi' },
    { language: 'Hiri Motu', languageCode: 'ho' },
    { language: 'Hungarian', languageCode: 'hu' },
    { language: 'Interlingua', languageCode: 'ia' },
    { language: 'Indonesian', languageCode: 'id' },
    { language: 'Interlingue', languageCode: 'ie' },
    { language: 'Irish', languageCode: 'ga' },
    { language: 'Igbo', languageCode: 'ig' },
    { language: 'Inupiaq', languageCode: 'ik' },
    { language: 'Ido', languageCode: 'io' },
    { language: 'Icelandic', languageCode: 'is' },
    { language: 'Italian', languageCode: 'it' },
    { language: 'Inuktitut', languageCode: 'iu' },
    { language: 'Japanese', languageCode: 'ja' },
    { language: 'Javanese', languageCode: 'jv' },
    { language: 'Kalaallisut, Greenlandic', languageCode: 'kl' },
    { language: 'Kannada', languageCode: 'kn' },
    { language: 'Kanuri', languageCode: 'kr' },
    { language: 'Kashmiri', languageCode: 'ks' },
    { language: 'Kazakh', languageCode: 'kk' },
    { language: 'Central Khmer', languageCode: 'km' },
    { language: 'Kikuyu, Gikuyu', languageCode: 'ki' },
    { language: 'Kinyarwanda', languageCode: 'rw' },
    { language: 'Kirghiz, Kyrgyz', languageCode: 'ky' },
    { language: 'Komi', languageCode: 'kv' },
    { language: 'Kongo', languageCode: 'kg' },
    { language: 'Korean', languageCode: 'ko' },
    { language: 'Kurdish', languageCode: 'ku' },
    { language: 'Kuanyama, Kwanyama', languageCode: 'kj' },
    { language: 'Latin', languageCode: 'la' },
    { language: 'Luxembourgish, Letzeburgesch', languageCode: 'lb' },
    { language: 'Ganda', languageCode: 'lg' },
    { language: 'Limburgan, Limburger, Limburgish', languageCode: 'li' },
    { language: 'Lingala', languageCode: 'ln' },
    { language: 'Lao', languageCode: 'lo' },
    { language: 'Lithuanian', languageCode: 'lt' },
    { language: 'Luba-Katanga', languageCode: 'lu' },
    { language: 'Latvian', languageCode: 'lv' },
    { language: 'Manx', languageCode: 'gv' },
    { language: 'Macedonian', languageCode: 'mk' },
    { language: 'Malagasy', languageCode: 'mg' },
    { language: 'Malay', languageCode: 'ms' },
    { language: 'Malayalam', languageCode: 'ml' },
    { language: 'Maltese', languageCode: 'mt' },
    { language: 'Maori', languageCode: 'mi' },
    { language: 'Marathi', languageCode: 'mr' },
    { language: 'Marshallese', languageCode: 'mh' },
    { language: 'Mongolian', languageCode: 'mn' },
    { language: 'Nauru', languageCode: 'na' },
    { language: 'Navajo, Navaho', languageCode: 'nv' },
    { language: 'North Ndebele', languageCode: 'nd' },
    { language: 'Nepali', languageCode: 'ne' },
    { language: 'Ndonga', languageCode: 'ng' },
    { language: 'Norwegian Bokmål', languageCode: 'nb' },
    { language: 'Norwegian Nynorsk', languageCode: 'nn' },
    { language: 'Norwegian', languageCode: 'no' },
    { language: 'Sichuan Yi, Nuosu', languageCode: 'ii' },
    { language: 'South Ndebele', languageCode: 'nr' },
    { language: 'Occitan', languageCode: 'oc' },
    { language: 'Ojibwa', languageCode: 'oj' },
    {
      language:
        'Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian',
      languageCode: 'cu'
    },
    { language: 'Oromo', languageCode: 'om' },
    { language: 'Oriya', languageCode: 'or' },
    { language: 'Ossetian, Ossetic', languageCode: 'os' },
    { language: 'Panjabi, Punjabi', languageCode: 'pa' },
    { language: 'Pali', languageCode: 'pi' },
    { language: 'Persian', languageCode: 'fa' },
    { language: 'Polabian', languageCode: 'pox' },
    { language: 'Polish', languageCode: 'pl' },
    { language: 'Pashto, Pushto', languageCode: 'ps' },
    { language: 'Portuguese', languageCode: 'pt' },
    { language: 'Quechua', languageCode: 'qu' },
    { language: 'Romansh', languageCode: 'rm' },
    { language: 'Rundi', languageCode: 'rn' },
    { language: 'Romanian, Moldavian, Moldovan', languageCode: 'ro' },
    { language: 'Russian', languageCode: 'ru' },
    { language: 'Sanskrit', languageCode: 'sa' },
    { language: 'Sardinian', languageCode: 'sc' },
    { language: 'Sindhi', languageCode: 'sd' },
    { language: 'Northern Sami', languageCode: 'se' },
    { language: 'Samoan', languageCode: 'sm' },
    { language: 'Sango', languageCode: 'sg' },
    { language: 'Serbian', languageCode: 'sr' },
    { language: 'Gaelic, Scottish Gaelic', languageCode: 'gd' },
    { language: 'Shona', languageCode: 'sn' },
    { language: 'Sinhala, Sinhalese', languageCode: 'si' },
    { language: 'Slovak', languageCode: 'sk' },
    { language: 'Slovenian', languageCode: 'sl' },
    { language: 'Somali', languageCode: 'so' },
    { language: 'Southern Sotho', languageCode: 'st' },
    { language: 'Spanish, Castilian', languageCode: 'es-ES' },
    { language: 'Sundanese', languageCode: 'su' },
    { language: 'Swahili', languageCode: 'sw' },
    { language: 'Swati', languageCode: 'ss' },
    { language: 'Swedish', languageCode: 'sv' },
    { language: 'Tamil', languageCode: 'ta' },
    { language: 'Telugu', languageCode: 'te' },
    { language: 'Tajik', languageCode: 'tg' },
    { language: 'Thai', languageCode: 'th' },
    { language: 'Tigrinya', languageCode: 'ti' },
    { language: 'Tibetan', languageCode: 'bo' },
    { language: 'Turkmen', languageCode: 'tk' },
    { language: 'Tagalog', languageCode: 'tl' },
    { language: 'Tswana', languageCode: 'tn' },
    { language: 'Tonga (Tonga Islands)', languageCode: 'to' },
    { language: 'Turkish', languageCode: 'tr' },
    { language: 'Tsonga', languageCode: 'ts' },
    { language: 'Tatar', languageCode: 'tt' },
    { language: 'Twi', languageCode: 'tw' },
    { language: 'Tahitian', languageCode: 'ty' },
    { language: 'Uighur, Uyghur', languageCode: 'ug' },
    { language: 'Ukrainian', languageCode: 'uk' },
    { language: 'Urdu', languageCode: 'ur' },
    { language: 'Uzbek', languageCode: 'uz' },
    { language: 'Venda', languageCode: 've' },
    { language: 'Vietnamese', languageCode: 'vi' },
    { language: 'Volapük', languageCode: 'vo' },
    { language: 'Walloon', languageCode: 'wa' },
    { language: 'Welsh', languageCode: 'cy' },
    { language: 'Wolof', languageCode: 'wo' },
    { language: 'Western Frisian', languageCode: 'fy' },
    { language: 'Xhosa', languageCode: 'xh' },
    { language: 'Yiddish', languageCode: 'yi' },
    { language: 'Yoruba', languageCode: 'yo' },
    { language: 'Zhuang, Chuang', languageCode: 'za' },
    { language: 'Zulu', languageCode: 'zu' }
  ]
};
