export class DateTimeFormats {
  private static readonly concatFormats = [
    'MDYYYY--Hms',
    'MDYY--Hms',
    'DMYYYY--Hms',
    'DMYY--Hms',
    'YYYYMD--Hms',
    'YYMD--Hms',
    'YYYYDM--Hms',
    'YYDM--Hms',

    'MDYYYY--Hm',
    'MDYY--Hm',
    'DMYYYY--Hm',
    'DMYY--Hm',
    'YYYYMD--Hm',
    'YYMD--Hm',
    'YYYYDM--Hm',
    'YYDM--Hm',

    'M/D/YYYY--H:m',
    'M/D/YY--H:m',
    'D/M/YYYY--H:m',
    'D/M/YY--H:m',
    'YYYY/M/D--H:m',
    'YY/M/D--H:m',
    'YYYY/D/M--H:m',
    'YY/D/M--H:m',

    'M/D/YYYY--H:m:s',
    'M/D/YY--H:m:s',
    'D/M/YYYY--H:m:s',
    'D/M/YY--H:m:s',
    'YYYY/M/D--H:m:s',
    'YY/M/D--H:m:s',
    'YYYY/D/M--H:m:s',
    'YY/D/M--H:m:s',

    'M/D/YYYY--Hm',
    'M/D/YY--Hm',
    'D/M/YYYY--Hm',
    'D/M/YY--Hm',
    'YYYY/M/D--Hm',
    'YY/M/D--Hm',
    'YYYY/D/M--Hm',
    'YY/D/M--Hm',

    'M/D/YYYY--Hms',
    'M/D/YY--Hms',
    'D/M/YYYY--Hms',
    'D/M/YY--Hms',
    'YYYY/M/D--Hms',
    'YY/M/D--Hms',
    'YYYY/D/M--Hms',
    'YY/D/M--Hms',

    'M/D/YYYY--h:m A',
    'M/D/YY--h:m A',
    'D/M/YYYY--h:m A',
    'D/M/YY--h:m A',
    'YYYY/M/D--h:m A',
    'YY/M/D--h:m A',
    'YYYY/D/M--h:m A',
    'YY/D/M--h:m A',

    'M/D/YYYY--h:m:s A',
    'M/D/YY--h:m:s A',
    'D/M/YYYY--h:m:s A',
    'D/M/YY--h:m:s A',
    'YYYY/M/D--h:m:s A',
    'YY/M/D--h:m:s A',
    'YYYY/D/M--h:m:s A',
    'YY/D/M--h:m:s A',

    'M--D--YYYY',
    'M--D--YY',
    'D--M--YYYY',
    'D--M--YY',
    'YYYY--M--D',
    'YY--M--D',
    'YYYY--D--M',
    'YY--D--M'
  ];
  private static readonly unconcatFormats = [
    'MDYYYYHm',
    'MDYYHm',
    'DMYYYYHm',
    'DMYYHm',
    'YYYYMDHm',
    'YYMDHm',
    'YYYYDMHm',
    'YYDMHm',

    'MDYYYYHms',
    'MDYYHms',
    'DMYYYYHms',
    'DMYYHms',
    'YYYYMDHms',
    'YYMDHms',
    'YYYYDMHms',
    'YYDMHms',

    'M/D/YYYY',
    'M/D/YY',
    'D/M/YYYY',
    'D/M/YY',
    'YYYY/M/D',
    'YY/M/D',
    'YYYY/D/M',
    'YY/D/M',

    'M/D/YYYY H:m',
    'M/D/YY H:m',
    'D/M/YYYY H:m',
    'D/M/YY H:m',
    'YYYY/M/D H:m',
    'YY/M/D H:m',
    'YYYY/D/M H:m',
    'YY/D/M H:m',

    'M/D/YYYYH:m',
    'M/D/YYH:m',
    'D/M/YYYYH:m',
    'D/M/YYH:m',
    'YYYY/M/DH:m',
    'YY/M/DH:m',
    'YYYY/D/MH:m',
    'YY/D/MH:m',

    'M/D/YYYY H:m:s',
    'M/D/YY H:m:s',
    'D/M/YYYY H:m:s',
    'D/M/YY H:m:s',
    'YYYY/M/D H:m:s',
    'YY/M/D H:m:s',
    'YYYY/D/M H:m:s',
    'YY/D/M H:m:s',

    'M/D/YYYY h:m A',
    'M/D/YY h:m A',
    'D/M/YYYY h:m A',
    'D/M/YY h:m A',
    'YYYY/M/D h:m A',
    'YY/M/D h:m A',
    'YYYY/D/M h:m A',
    'YY/D/M h:m A',

    'M/D/YYYY h:m:s A',
    'M/D/YY h:m:s A',
    'D/M/YYYY h:m:s A',
    'D/M/YY h:m:s A',
    'YYYY/M/D h:m:s A',
    'YY/M/D h:m:s A',
    'YYYY/D/M h:m:s A',
    'YY/D/M h:m:s A',

    'M.D.YYYY H:m',
    'M.D.YY H:m',
    'D.M.YYYY H:m',
    'D.M.YY H:m',
    'YYYY.M.D H:m',
    'YY.M.D H:m',
    'YYYY.D.M H:m',
    'YY.D.M H:m',

    'M-D-YYYYTH:m:sZ',
    'M-D-YYTH:m:sZ',
    'D-M-YYYYTH:m:sZ',
    'D-M-YYTH:m:sZ',
    'YYYY-M-DTH:m:sZ',
    'YY-M-DTH:m:sZ',
    'YYYY-D-MTH:m:sZ',
    'YY-D-MTH:m:sZ',

    'M-D-YYYYTH:m:s',
    'M-D-YYTH:m:s',
    'D-M-YYYYTH:m:s',
    'D-M-YYTH:m:s',
    'YYYY-M-DTH:m:s',
    'YY-M-DTH:m:s',
    'YYYY-D-MTH:m:s',
    'YY-D-MTH:m:s'
  ];
  private static readonly specialFormats = [
    'M/D/YYYYH:m:s',
    'M/D/YYH:m:s',
    'D/M/YYYYH:m:s',
    'D/M/YYH:m:s',
    'YYYY/M/DH:m:s',
    'YY/M/DH:m:s',
    'YYYY/D/MH:m:s',
    'YY/D/MH:m:s',

    'M/D/YYYYH:m:sBNPro',
    'M/D/YYH:m:sBNPro',
    'D/M/YYYYH:m:sBNPro',
    'D/M/YYH:m:sBNPro',
    'YYYY/M/DH:m:sBNPro',
    'YY/M/DH:m:sBNPro',
    'YYYY/D/MH:m:sBNPro',
    'YY/D/MH:m:sBNPro',

    'M/D/YYYY  h:m:sA',
    'M/D/YY  h:m:sA',
    'D/M/YYYY  h:m:sA',
    'D/M/YY  h:m:sA',
    'YYYY/M/D  h:m:sA',
    'YY/M/D  h:m:sA',
    'YYYY/D/M  h:m:sA',
    'YY/D/M  h:m:sA',

    'M/D/YYYY H.m.s',
    'M/D/YY H.m.s',
    'D/M/YYYY H.m.s',
    'D/M/YY H.m.s',
    'YYYY/M/D H.m.s',
    'YY/M/D H.m.s',
    'YYYY/D/M H.m.s',
    'YY/D/M H.m.s',

  ];

  static getSupportedFormats() {
    return this.concatFormats
    .concat(this.unconcatFormats)
    .concat(this.specialFormats);
  }
}
